### ISSUE TITLE
Can't read swagger.json

### ISSUE THREAD

**Issue by rolandkofler** [jpmorganchase/cakeshop#3]
#### System information

Cakeshop version or commit hash: <0.9>

Geth/Quorum version testing against: `geth version`

OS & Version: Linux/Docker

#### Expected behavior
show the API

#### Actual behavior
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://172.17.0.2:8080/cakeshop/api/swagger.json"}]}

#### Steps to reproduce the behavior
Navigate to API see error

**Comment by chetan** [comment]
I wasn't able to reproduce this error. What OS/Browser are you using?

**Comment by rolandkofler** [comment]
Ubuntu 16.04, Chromium Version 53.0.2785.143
Pretty sure it has nothing to do with the Browser ;-)
![image](https://cloud.githubusercontent.com/assets/979444/21323688/f0c7028c-c61e-11e6-8b77-0d1bedc4b506.png)

**Comment by chetan** [comment]
Well I know we definitely have a couple of issues with MSIE, so just wanted to make sure it's not that. Looks like it's the same as this issue - 

https://groups.google.com/forum/#!topic/swagger-swaggersocket/dpbIf87x4c8

Not sure why we haven't seen this before, since it sounds like we *should* be getting it too. I'll push a fix for that shortly.
